# Generated by Django 4.0 on 2022-01-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcitian',
            name='fmail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='FCIT Email Adress'),
        ),
    ]
